BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0001_supabase_baseline

CREATE EXTENSION IF NOT EXISTS pgcrypto;;

DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_type t
                JOIN pg_namespace n ON n.oid = t.typnamespace
                WHERE n.nspname = 'public'
                  AND t.typname = 'eventlah_user_role'
            ) THEN
                CREATE TYPE public.eventlah_user_role AS ENUM (
                    'OWNER',
                    'ADMIN'
                );
            END IF;
        END
        $$;;

CREATE OR REPLACE FUNCTION public.set_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $function$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $function$;;

CREATE TABLE IF NOT EXISTS public.users (
            id UUID PRIMARY KEY
                REFERENCES auth.users(id)
                ON DELETE CASCADE,

            email TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL DEFAULT '',
            picture_url TEXT NOT NULL DEFAULT '',

            role public.eventlah_user_role NOT NULL DEFAULT 'ADMIN',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );;

CREATE INDEX IF NOT EXISTS idx_users_active
        ON public.users (is_active);;

CREATE INDEX IF NOT EXISTS idx_users_role
        ON public.users (role);;

CREATE TABLE IF NOT EXISTS public.events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            name TEXT NOT NULL,
            event_type TEXT NOT NULL DEFAULT 'company_dinner',
            company_name TEXT NOT NULL DEFAULT '',

            date TEXT NOT NULL DEFAULT '',
            time TEXT NOT NULL DEFAULT '',
            venue TEXT NOT NULL DEFAULT '',
            theme TEXT NOT NULL DEFAULT '',

            guest_count INTEGER NOT NULL DEFAULT 0,
            present_count INTEGER NOT NULL DEFAULT 0,

            user_id UUID NOT NULL
                REFERENCES public.users(id)
                ON DELETE RESTRICT,

            logo TEXT NOT NULL DEFAULT '',
            wedding_invitation TEXT NOT NULL DEFAULT '',

            logo_storage_path TEXT NOT NULL DEFAULT '',
            logo_filename TEXT NOT NULL DEFAULT '',
            logo_mime_type TEXT NOT NULL DEFAULT '',

            invitation_storage_path TEXT NOT NULL DEFAULT '',
            invitation_filename TEXT NOT NULL DEFAULT '',
            invitation_mime_type TEXT NOT NULL DEFAULT '',

            guest_list_storage_path TEXT NOT NULL DEFAULT '',
            guest_list_filename TEXT NOT NULL DEFAULT '',
            guest_list_mime_type TEXT NOT NULL DEFAULT '',
            guest_list_uploaded_at TIMESTAMPTZ NULL,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT events_event_type_check
                CHECK (
                    event_type IN (
                        'company_dinner',
                        'wedding_dinner',
                        'sports_day'
                    )
                ),

            CONSTRAINT events_guest_count_check
                CHECK (guest_count >= 0),

            CONSTRAINT events_present_count_check
                CHECK (
                    present_count >= 0
                    AND present_count <= guest_count
                )
        );;

CREATE INDEX IF NOT EXISTS idx_events_date
        ON public.events (date);;

CREATE INDEX IF NOT EXISTS idx_events_user_created
        ON public.events (user_id, created_at DESC);;

CREATE TABLE IF NOT EXISTS public.guests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            guest_id TEXT NOT NULL,

            name TEXT NOT NULL DEFAULT '',
            email TEXT NOT NULL DEFAULT '',
            phone TEXT NOT NULL DEFAULT '',

            status TEXT NOT NULL DEFAULT 'Absent',
            table_number TEXT NOT NULL DEFAULT 'TBD',

            amount NUMERIC(12, 2) NOT NULL DEFAULT 0,

            team_name TEXT NULL,

            qr_code TEXT NULL,
            qr_url TEXT NULL,

            email_sent BOOLEAN NOT NULL DEFAULT FALSE,

            full_data JSONB NOT NULL DEFAULT '{}'::jsonb,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT guests_event_guest_unique
                UNIQUE (event_id, guest_id)
        );;

CREATE INDEX IF NOT EXISTS idx_guests_event_status
        ON public.guests (event_id, status);;

CREATE INDEX IF NOT EXISTS idx_guests_event_updated
        ON public.guests (event_id, updated_at);;

CREATE INDEX IF NOT EXISTS idx_guests_event_name
        ON public.guests (event_id, name);;

CREATE INDEX IF NOT EXISTS idx_guests_email
        ON public.guests (email);;

CREATE TABLE IF NOT EXISTS public.scanner_devices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            device_id TEXT NOT NULL,
            device_name TEXT NOT NULL DEFAULT '',

            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            total_scans INTEGER NOT NULL DEFAULT 0,

            last_used TIMESTAMPTZ NULL,

            assigned_by UUID NULL
                REFERENCES public.users(id)
                ON DELETE SET NULL,

            assigned_at TIMESTAMPTZ NULL,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT scanner_event_device_unique
                UNIQUE (event_id, device_id),

            CONSTRAINT scanner_total_scans_check
                CHECK (total_scans >= 0)
        );;

CREATE INDEX IF NOT EXISTS idx_scanners_event_active
        ON public.scanner_devices (event_id, is_active);;

CREATE TABLE IF NOT EXISTS public.stalls (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            stall_name TEXT NOT NULL,
            description TEXT NULL,
            qr_code TEXT NULL,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );;

CREATE INDEX IF NOT EXISTS idx_stalls_event
        ON public.stalls (event_id);;

CREATE TABLE IF NOT EXISTS public.menu_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            stall_id BIGINT NOT NULL
                REFERENCES public.stalls(id)
                ON DELETE CASCADE,

            item_name TEXT NOT NULL,
            description TEXT NULL,
            price NUMERIC(12, 2) NOT NULL DEFAULT 0,
            image_url TEXT NULL,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );;

CREATE INDEX IF NOT EXISTS idx_menu_items_stall
        ON public.menu_items (stall_id);;

CREATE TABLE IF NOT EXISTS public.transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            guest_id TEXT NOT NULL,

            stall_id BIGINT NULL
                REFERENCES public.stalls(id)
                ON DELETE SET NULL,

            menu_item_id BIGINT NULL
                REFERENCES public.menu_items(id)
                ON DELETE SET NULL,

            item_name TEXT NULL,

            quantity INTEGER NOT NULL DEFAULT 1,
            amount NUMERIC(12, 2) NOT NULL DEFAULT 0,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT transactions_quantity_check
                CHECK (quantity > 0)
        );;

CREATE INDEX IF NOT EXISTS idx_transactions_event
        ON public.transactions (event_id);;

CREATE INDEX IF NOT EXISTS idx_transactions_event_guest_time
        ON public.transactions (event_id, guest_id, created_at);;

CREATE TABLE IF NOT EXISTS public.checkins (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            guest_id TEXT NOT NULL,
            scanner_id TEXT NULL,

            result TEXT NOT NULL,

            checked_in_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );;

CREATE INDEX IF NOT EXISTS idx_checkins_event_time
        ON public.checkins (event_id, checked_in_at);;

CREATE INDEX IF NOT EXISTS idx_checkins_event_guest
        ON public.checkins (event_id, guest_id);;

CREATE TABLE IF NOT EXISTS public.checkin_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            guest_id TEXT NOT NULL,
            scanner_id TEXT NOT NULL,
            result TEXT NOT NULL,

            checked_in_at TIMESTAMPTZ NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );;

CREATE INDEX IF NOT EXISTS idx_checkin_history_event
        ON public.checkin_history (event_id, created_at DESC);;

CREATE TABLE IF NOT EXISTS public.email_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            guest_id TEXT NOT NULL,

            email_type TEXT NOT NULL DEFAULT 'invitation',

            recipient TEXT NOT NULL,
            subject TEXT NOT NULL,
            html_content TEXT NOT NULL,
            plain_text TEXT NOT NULL DEFAULT '',

            status TEXT NOT NULL DEFAULT 'queued',
            attempts INTEGER NOT NULL DEFAULT 0,

            available_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            locked_at TIMESTAMPTZ NULL,
            sent_at TIMESTAMPTZ NULL,
            last_error TEXT NULL,
            provider_message_id TEXT NULL,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT email_jobs_attempts_check
                CHECK (attempts >= 0),

            CONSTRAINT email_jobs_status_check
                CHECK (
                    status IN (
                        'queued',
                        'processing',
                        'sent',
                        'failed',
                        'cancelled'
                    )
                ),

            CONSTRAINT email_jobs_event_guest_type_unique
                UNIQUE (event_id, guest_id, email_type)
        );;

CREATE INDEX IF NOT EXISTS idx_email_jobs_claim
        ON public.email_jobs (status, available_at, id);;

CREATE INDEX IF NOT EXISTS idx_email_jobs_event
        ON public.email_jobs (event_id);;

CREATE TABLE IF NOT EXISTS public.winners (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            guest_id TEXT NOT NULL,

            name TEXT NULL,
            prize TEXT NULL,
            prize_name TEXT NULL,
            prize_value TEXT NULL,
            prize_image TEXT NULL,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT winners_event_guest_unique
                UNIQUE (event_id, guest_id)
        );;

CREATE INDEX IF NOT EXISTS idx_winners_event
        ON public.winners (event_id);;

CREATE TABLE IF NOT EXISTS public.pre_draw_winners (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            guest_id TEXT NOT NULL,
            name TEXT NOT NULL,

            prize_name TEXT NOT NULL DEFAULT '',
            prize_value TEXT NOT NULL DEFAULT '',
            image_url TEXT NOT NULL DEFAULT '',

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT pre_draw_winners_event_guest_unique
                UNIQUE (event_id, guest_id)
        );;

CREATE INDEX IF NOT EXISTS idx_pre_draw_winners_event
        ON public.pre_draw_winners (event_id);;

CREATE TABLE IF NOT EXISTS public.pre_draw_prizes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            name TEXT NOT NULL,
            value TEXT NOT NULL DEFAULT '',
            image_url TEXT NOT NULL DEFAULT '',

            winner_count INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'draft',

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT pre_draw_prizes_winner_count_positive
                CHECK (winner_count > 0),

            CONSTRAINT pre_draw_prizes_sort_order_nonnegative
                CHECK (sort_order >= 0),

            CONSTRAINT pre_draw_prizes_status_check
                CHECK (
                    status IN (
                        'draft',
                        'ready',
                        'generated',
                        'archived'
                    )
                )
        );;

CREATE INDEX IF NOT EXISTS idx_pre_draw_prizes_event_order
        ON public.pre_draw_prizes (event_id, sort_order);;

CREATE TABLE IF NOT EXISTS public.event_assets (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            event_id BIGINT NOT NULL
                REFERENCES public.events(id)
                ON DELETE CASCADE,

            asset_type TEXT NOT NULL,

            storage_bucket TEXT NOT NULL DEFAULT 'event-assets',
            storage_path TEXT NOT NULL,

            filename TEXT NOT NULL DEFAULT '',
            mime_type TEXT NOT NULL DEFAULT '',
            size_bytes BIGINT NULL,

            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT event_assets_type_check
                CHECK (
                    asset_type IN (
                        'logo',
                        'invitation',
                        'guest_list'
                    )
                ),

            CONSTRAINT event_assets_event_type_unique
                UNIQUE (event_id, asset_type)
        );;

CREATE INDEX IF NOT EXISTS idx_event_assets_event
        ON public.event_assets (event_id);;

DROP TRIGGER IF EXISTS trg_users_updated_at
        ON public.users;

        CREATE TRIGGER trg_users_updated_at
        BEFORE UPDATE ON public.users
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_events_updated_at
        ON public.events;

        CREATE TRIGGER trg_events_updated_at
        BEFORE UPDATE ON public.events
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_guests_updated_at
        ON public.guests;

        CREATE TRIGGER trg_guests_updated_at
        BEFORE UPDATE ON public.guests
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_scanners_updated_at
        ON public.scanner_devices;

        CREATE TRIGGER trg_scanners_updated_at
        BEFORE UPDATE ON public.scanner_devices
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_stalls_updated_at
        ON public.stalls;

        CREATE TRIGGER trg_stalls_updated_at
        BEFORE UPDATE ON public.stalls
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_menu_items_updated_at
        ON public.menu_items;

        CREATE TRIGGER trg_menu_items_updated_at
        BEFORE UPDATE ON public.menu_items
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_pre_draw_prizes_updated_at
        ON public.pre_draw_prizes;

        CREATE TRIGGER trg_pre_draw_prizes_updated_at
        BEFORE UPDATE ON public.pre_draw_prizes
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_email_jobs_updated_at
        ON public.email_jobs;

        CREATE TRIGGER trg_email_jobs_updated_at
        BEFORE UPDATE ON public.email_jobs
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

DROP TRIGGER IF EXISTS trg_event_assets_updated_at
        ON public.event_assets;

        CREATE TRIGGER trg_event_assets_updated_at
        BEFORE UPDATE ON public.event_assets
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path TO 'public'
        AS $function$
        BEGIN
            INSERT INTO public.users (
                id,
                email,
                name,
                picture_url
            )
            VALUES (
                NEW.id,
                COALESCE(NEW.email, ''),
                COALESCE(NEW.raw_user_meta_data ->> 'full_name', ''),
                COALESCE(NEW.raw_user_meta_data ->> 'avatar_url', '')
            )
            ON CONFLICT (id) DO UPDATE
            SET
                email = EXCLUDED.email,
                name = CASE
                    WHEN EXCLUDED.name <> ''
                    THEN EXCLUDED.name
                    ELSE public.users.name
                END,
                picture_url = CASE
                    WHEN EXCLUDED.picture_url <> ''
                    THEN EXCLUDED.picture_url
                    ELSE public.users.picture_url
                END,
                updated_at = now();

            RETURN NEW;
        END;
        $function$;;

DROP TRIGGER IF EXISTS on_auth_user_created
        ON auth.users;

        CREATE TRIGGER on_auth_user_created
        AFTER INSERT OR UPDATE ON auth.users
        FOR EACH ROW
        EXECUTE FUNCTION public.handle_new_auth_user();;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.scanner_devices ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.stalls ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.checkin_history ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.email_jobs ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.winners ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.pre_draw_winners ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.pre_draw_prizes ENABLE ROW LEVEL SECURITY;;

ALTER TABLE public.event_assets ENABLE ROW LEVEL SECURITY;;

INSERT INTO alembic_version (version_num) VALUES ('0001_supabase_baseline') RETURNING alembic_version.version_num;

COMMIT;

