"""Supabase baseline schema.

Revision ID: 0001_supabase_baseline
Revises:
Create Date: 2026-09-15

This baseline describes the EventLah application schema that already exists in
Supabase. It is intended for a fresh application database. The existing
production Supabase database was stamped at this revision and must not be
upgraded through this migration.
"""
from alembic import op

revision = "0001_supabase_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE n.nspname = 'public'
              AND t.typname = 'eventlah_user_role'
        ) THEN
            CREATE TYPE public.eventlah_user_role AS ENUM ('OWNER', 'ADMIN');
        END IF;
    END
    $$;
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION public.set_updated_at()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $function$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $function$;
    """)

    op.execute("""
    CREATE TABLE public.users (
        id UUID PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL DEFAULT '',
        picture_url TEXT NOT NULL DEFAULT '',
        role public.eventlah_user_role NOT NULL DEFAULT 'ADMIN'::public.eventlah_user_role,
        is_active BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT users_id_fkey
            FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
    );
    """)

    op.execute("""
    CREATE TABLE public.events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        event_type TEXT NOT NULL DEFAULT 'company_dinner',
        company_name TEXT NOT NULL DEFAULT '',
        date TEXT NOT NULL DEFAULT '',
        time TEXT NOT NULL DEFAULT '',
        venue TEXT NOT NULL DEFAULT '',
        theme TEXT NOT NULL DEFAULT '',
        guest_count INTEGER NOT NULL DEFAULT 0,
        present_count INTEGER NOT NULL DEFAULT 0,
        user_id UUID NOT NULL,
        logo TEXT NOT NULL DEFAULT '',
        wedding_invitation TEXT NOT NULL DEFAULT '',
        logo_storage_path TEXT NOT NULL DEFAULT '',
        logo_filename TEXT NOT NULL DEFAULT '',
        logo_mime_type TEXT NOT NULL DEFAULT '',
        invitation_storage_path TEXT NOT NULL DEFAULT '',
        invitation_filename TEXT NOT NULL DEFAULT '',
        invitation_mime_type TEXT NOT NULL DEFAULT '',
        guest_list_storage_path TEXT NOT NULL DEFAULT '',
        guest_list_filename TEXT NOT NULL DEFAULT '',
        guest_list_mime_type TEXT NOT NULL DEFAULT '',
        guest_list_uploaded_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT events_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT,
        CONSTRAINT events_event_type_check
            CHECK (event_type IN ('company_dinner', 'wedding_dinner', 'sports_day')),
        CONSTRAINT events_guest_count_check
            CHECK (guest_count >= 0),
        CONSTRAINT events_present_count_check
            CHECK (present_count >= 0 AND present_count <= guest_count)
    );
    """)

    op.execute("""
    CREATE TABLE public.guests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        guest_id TEXT NOT NULL,
        name TEXT NOT NULL DEFAULT '',
        email TEXT NOT NULL DEFAULT '',
        phone TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'Absent',
        table_number TEXT NOT NULL DEFAULT 'TBD',
        amount NUMERIC(12,2) NOT NULL DEFAULT 0,
        team_name TEXT,
        qr_code TEXT,
        qr_url TEXT,
        email_sent BOOLEAN NOT NULL DEFAULT false,
        full_data JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT guests_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT guests_event_guest_unique
            UNIQUE (event_id, guest_id)
    );
    """)

    op.execute("""
    CREATE TABLE public.scanner_devices (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        device_id TEXT NOT NULL,
        device_name TEXT NOT NULL DEFAULT '',
        is_active BOOLEAN NOT NULL DEFAULT true,
        total_scans INTEGER NOT NULL DEFAULT 0,
        last_used TIMESTAMPTZ,
        assigned_by UUID,
        assigned_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT scanner_event_device_unique
            UNIQUE (event_id, device_id),
        CONSTRAINT scanner_devices_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT scanner_devices_assigned_by_fkey
            FOREIGN KEY (assigned_by) REFERENCES public.users(id) ON DELETE SET NULL,
        CONSTRAINT scanner_total_scans_check
            CHECK (total_scans >= 0)
    );
    """)

    op.execute("""
    CREATE TABLE public.stalls (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        stall_name TEXT NOT NULL,
        description TEXT,
        qr_code TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT stalls_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE
    );
    """)

    op.execute("""
    CREATE TABLE public.menu_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stall_id BIGINT NOT NULL,
        item_name TEXT NOT NULL,
        description TEXT,
        price NUMERIC(12,2) NOT NULL DEFAULT 0,
        image_url TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT menu_items_stall_id_fkey
            FOREIGN KEY (stall_id) REFERENCES public.stalls(id) ON DELETE CASCADE
    );
    """)

    op.execute("""
    CREATE TABLE public.transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        guest_id TEXT NOT NULL,
        stall_id BIGINT,
        menu_item_id BIGINT,
        item_name TEXT,
        quantity INTEGER NOT NULL DEFAULT 1,
        amount NUMERIC(12,2) NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT transactions_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT transactions_stall_id_fkey
            FOREIGN KEY (stall_id) REFERENCES public.stalls(id) ON DELETE SET NULL,
        CONSTRAINT transactions_menu_item_id_fkey
            FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id) ON DELETE SET NULL,
        CONSTRAINT transactions_quantity_check
            CHECK (quantity > 0)
    );
    """)

    op.execute("""
    CREATE TABLE public.checkins (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        guest_id TEXT NOT NULL,
        scanner_id TEXT,
        result TEXT NOT NULL,
        checked_in_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT checkins_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE
    );
    """)

    op.execute("""
    CREATE TABLE public.checkin_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        guest_id TEXT NOT NULL,
        scanner_id TEXT NOT NULL,
        result TEXT NOT NULL,
        checked_in_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT checkin_history_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE
    );
    """)

    op.execute("""
    CREATE TABLE public.email_jobs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT,
        guest_id TEXT NOT NULL,
        email_type TEXT NOT NULL DEFAULT 'invitation',
        recipient TEXT NOT NULL,
        subject TEXT NOT NULL,
        html_content TEXT NOT NULL,
        plain_text TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'queued',
        attempts INTEGER NOT NULL DEFAULT 0,
        available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        locked_at TIMESTAMPTZ,
        sent_at TIMESTAMPTZ,
        last_error TEXT,
        provider_message_id TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT email_jobs_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT email_jobs_event_guest_type_unique
            UNIQUE (event_id, guest_id, email_type),
        CONSTRAINT email_jobs_attempts_check
            CHECK (attempts >= 0),
        CONSTRAINT email_jobs_status_check
            CHECK (status IN ('queued', 'processing', 'sent', 'failed', 'cancelled'))
    );
    """)

    op.execute("""
    CREATE TABLE public.winners (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        guest_id TEXT NOT NULL,
        name TEXT,
        prize TEXT,
        prize_name TEXT,
        prize_value TEXT,
        prize_image TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT winners_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT winners_event_guest_unique
            UNIQUE (event_id, guest_id)
    );
    """)

    op.execute("""
    CREATE TABLE public.pre_draw_winners (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        guest_id TEXT NOT NULL,
        name TEXT NOT NULL,
        prize_name TEXT NOT NULL DEFAULT '',
        prize_value TEXT NOT NULL DEFAULT '',
        image_url TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT pre_draw_winners_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT pre_draw_winners_event_guest_unique
            UNIQUE (event_id, guest_id)
    );
    """)

    op.execute("""
    CREATE TABLE public.pre_draw_prizes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        name TEXT NOT NULL,
        value TEXT NOT NULL DEFAULT '',
        image_url TEXT NOT NULL DEFAULT '',
        winner_count INTEGER NOT NULL DEFAULT 1,
        sort_order INTEGER NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'draft',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT pre_draw_prizes_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT pre_draw_prizes_winner_count_positive
            CHECK (winner_count > 0),
        CONSTRAINT pre_draw_prizes_sort_order_nonnegative
            CHECK (sort_order >= 0),
        CONSTRAINT pre_draw_prizes_status_check
            CHECK (status IN ('draft', 'ready', 'generated', 'archived'))
    );
    """)

    op.execute("""
    CREATE TABLE public.event_assets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        asset_type TEXT NOT NULL,
        storage_bucket TEXT NOT NULL DEFAULT 'event-assets',
        storage_path TEXT NOT NULL,
        filename TEXT NOT NULL DEFAULT '',
        mime_type TEXT NOT NULL DEFAULT '',
        size_bytes BIGINT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT event_assets_event_id_fkey
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
        CONSTRAINT event_assets_type_check
            CHECK (asset_type IN ('logo', 'invitation', 'guest_list')),
        CONSTRAINT event_assets_event_type_unique
            UNIQUE (event_id, asset_type)
    );
    """)

    indexes = [
        "CREATE INDEX idx_users_active ON public.users (is_active)",
        "CREATE INDEX idx_users_role ON public.users (role)",
        "CREATE INDEX idx_events_date ON public.events (date)",
        "CREATE INDEX idx_events_user_created ON public.events (user_id, created_at DESC)",
        "CREATE INDEX idx_guests_event_status ON public.guests (event_id, status)",
        "CREATE INDEX idx_guests_event_updated ON public.guests (event_id, updated_at)",
        "CREATE INDEX idx_guests_event_name ON public.guests (event_id, name)",
        "CREATE INDEX idx_guests_email ON public.guests (email)",
        "CREATE INDEX idx_scanners_event_active ON public.scanner_devices (event_id, is_active)",
        "CREATE INDEX idx_stalls_event ON public.stalls (event_id)",
        "CREATE INDEX idx_menu_items_stall ON public.menu_items (stall_id)",
        "CREATE INDEX idx_transactions_event ON public.transactions (event_id)",
        "CREATE INDEX idx_transactions_event_guest_time ON public.transactions (event_id, guest_id, created_at)",
        "CREATE INDEX idx_checkins_event_guest ON public.checkins (event_id, guest_id)",
        "CREATE INDEX idx_checkins_event_time ON public.checkins (event_id, checked_in_at)",
        "CREATE INDEX idx_checkin_history_event ON public.checkin_history (event_id, created_at DESC)",
        "CREATE INDEX idx_email_jobs_claim ON public.email_jobs (status, available_at, id)",
        "CREATE INDEX idx_email_jobs_event ON public.email_jobs (event_id)",
        "CREATE INDEX idx_winners_event ON public.winners (event_id)",
        "CREATE INDEX idx_pre_draw_winners_event ON public.pre_draw_winners (event_id)",
        "CREATE INDEX idx_pre_draw_prizes_event_order ON public.pre_draw_prizes (event_id, sort_order)",
        "CREATE INDEX idx_event_assets_event ON public.event_assets (event_id)",
    ]
    for statement in indexes:
        op.execute(statement)

    updated_tables = [
        "users", "events", "guests", "scanner_devices", "stalls",
        "menu_items", "pre_draw_prizes", "email_jobs", "event_assets",
    ]
    for table in updated_tables:
        op.execute(f"""
        CREATE TRIGGER trg_{'scanners' if table == 'scanner_devices' else table}_updated_at
        BEFORE UPDATE ON public.{table}
        FOR EACH ROW
        EXECUTE FUNCTION public.set_updated_at();
        """)

    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
    RETURNS trigger
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path TO 'public'
    AS $function$
    BEGIN
        INSERT INTO public.users (id, email, name, picture_url)
        VALUES (
            NEW.id,
            COALESCE(NEW.email, ''),
            COALESCE(NEW.raw_user_meta_data ->> 'full_name', ''),
            COALESCE(NEW.raw_user_meta_data ->> 'avatar_url', '')
        )
        ON CONFLICT (id) DO UPDATE
        SET
            email = EXCLUDED.email,
            name = CASE
                WHEN EXCLUDED.name <> '' THEN EXCLUDED.name
                ELSE public.users.name
            END,
            picture_url = CASE
                WHEN EXCLUDED.picture_url <> '' THEN EXCLUDED.picture_url
                ELSE public.users.picture_url
            END,
            updated_at = now();
        RETURN NEW;
    END;
    $function$;
    """)

    op.execute("""
    CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_auth_user();
    """)

    for table in (
        "users", "events", "guests", "scanner_devices", "stalls", "menu_items",
        "transactions", "checkins", "checkin_history", "email_jobs", "winners",
        "pre_draw_winners", "pre_draw_prizes", "event_assets",
    ):
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_auth_user()")

    for table in (
        "users", "events", "guests", "scanner_devices", "stalls", "menu_items",
        "transactions", "checkins", "checkin_history", "email_jobs", "winners",
        "pre_draw_winners", "pre_draw_prizes", "event_assets",
    ):
        op.execute(f"DROP TABLE IF EXISTS public.{table} CASCADE")

    op.execute("DROP FUNCTION IF EXISTS public.set_updated_at()")
    op.execute("DROP TYPE IF EXISTS public.eventlah_user_role")
