"""Add server-side authentication sessions.

Revision ID: 0004_server_side_auth_sessions
Revises: 0003_email_delivery_tracking
Create Date: 2026-09-18
"""

from alembic import op


revision = "0004_server_side_auth_sessions"
down_revision = "0003_email_delivery_tracking"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS public.auth_sessions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id_hash TEXT NOT NULL,
            user_id UUID NOT NULL,
            access_token_ciphertext TEXT NOT NULL,
            refresh_token_ciphertext TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at TIMESTAMPTZ NOT NULL,
            last_used_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            revoked_at TIMESTAMPTZ,

            CONSTRAINT auth_sessions_session_id_hash_unique
                UNIQUE (session_id_hash),

            CONSTRAINT auth_sessions_user_id_fkey
                FOREIGN KEY (user_id)
                REFERENCES public.users(id)
                ON DELETE CASCADE
        )
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_auth_sessions_user
        ON public.auth_sessions (user_id)
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires
        ON public.auth_sessions (expires_at)
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_auth_sessions_active
        ON public.auth_sessions (expires_at)
        WHERE revoked_at IS NULL
    """)

    op.execute("""
        ALTER TABLE public.auth_sessions ENABLE ROW LEVEL SECURITY
    """)


def downgrade() -> None:
    op.execute("""
        DROP TABLE IF EXISTS public.auth_sessions CASCADE
    """)
