# guest_management/services/google_drive_asset_service.py

"""
Google Drive asset service for EventLah.

Responsibilities
----------------
This service handles files associated with EventLah events.

Supported assets:

    Event
    ├── logo
    ├── invitation card
    └── guest list

Storage layout:

    EventLah Attendance/
        ├── Event Name/
        │   ├── logo.ext
        │   ├── invitation.ext
        │   └── guest_list.ext
        │
        └── ...

Authentication
--------------
OAuth is used instead of a service account because normal Google Drive
storage quota is not available to service accounts.

Environment variables:

    GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON
        Legacy/service-account setting. Retained for compatibility.

    GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE
        Legacy/service-account setting. Retained for compatibility.

    GOOGLE_DRIVE_OAUTH_CLIENT_FILE
        OAuth client JSON file.

    GOOGLE_DRIVE_OAUTH_TOKEN_FILE
        OAuth token JSON file.

    GOOGLE_DRIVE_ROOT_FOLDER_ID
        ID of the "EventLah Attendance" folder.

The OAuth token generated by google_drive_oauth_setup.py is used by
default.

Important
---------
This service does NOT modify the database.

Database updates belong to the repository/service layer.

This keeps Google Drive operations isolated and makes the event
creation flow easier to test and recover if Drive temporarily fails.
"""

from __future__ import annotations

import io
import json
import logging
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

from dotenv import load_dotenv

from google.auth.transport.requests import Request
from google.oauth2 import credentials as oauth_credentials
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaIoBaseDownload, MediaIoBaseUpload


# ----------------------------------------------------------------------
# Environment
# ----------------------------------------------------------------------

load_dotenv()


logger = logging.getLogger(__name__)


# ----------------------------------------------------------------------
# Constants
# ----------------------------------------------------------------------

DRIVE_SCOPES = [
    "https://www.googleapis.com/auth/drive",
]

FOLDER_MIME_TYPE = "application/vnd.google-apps.folder"

DEFAULT_ROOT_FOLDER_NAME = "EventLah Attendance"


# ----------------------------------------------------------------------
# Data object
# ----------------------------------------------------------------------


@dataclass(slots=True)
class DriveAsset:
    """Metadata describing a file stored in Google Drive."""

    file_id: str
    filename: str
    mime_type: str
    size: int = 0

    @property
    def id(self) -> str:
        """Compatibility alias for file_id."""
        return self.file_id

    @property
    def web_view_link(self) -> str:
        """Return a standard Google Drive browser URL."""
        if not self.file_id:
            return ""

        return (
            "https://drive.google.com/file/"
            f"{self.file_id}/view"
        )


# ----------------------------------------------------------------------
# Service
# ----------------------------------------------------------------------


class GoogleDriveAssetService:
    """
    Google Drive asset manager.

    OAuth is preferred.

    A service-account fallback is retained so existing deployments
    using the older configuration do not immediately break.
    """


    def __init__(
        self,
        *,
        root_folder_id: Optional[str] = None,
    ) -> None:

        self.root_folder_id = (
            root_folder_id
            or os.getenv("GOOGLE_DRIVE_ROOT_FOLDER_ID", "")
        ).strip()

        if not self.root_folder_id:
            raise ValueError(
                "GOOGLE_DRIVE_ROOT_FOLDER_ID is not configured."
            )

        self._drive = None

    # ==================================================================
    # AUTHENTICATION
    # ==================================================================

    def _get_drive(self):
        """
        Return an authenticated Google Drive API client.

        OAuth is preferred.

        Existing service-account configuration is supported as a
        fallback for compatibility.
        """

        if self._drive is not None:
            return self._drive

        # --------------------------------------------------------------
        # OAuth
        # --------------------------------------------------------------

        oauth_token_file = (
            os.getenv("GOOGLE_DRIVE_OAUTH_TOKEN_FILE", "")
            .strip()
        )

        oauth_client_file = (
            os.getenv("GOOGLE_DRIVE_OAUTH_CLIENT_FILE", "")
            .strip()
        )

        if oauth_token_file:
            token_path = Path(oauth_token_file)

            if not token_path.is_absolute():
                token_path = Path.cwd() / token_path

            if token_path.exists():

                try:
                    creds = (
                        oauth_credentials.Credentials
                        .from_authorized_user_file(
                            str(token_path),
                            DRIVE_SCOPES,
                        )
                    )

                    if creds.expired and creds.refresh_token:
                        creds.refresh(Request())

                        try:
                            token_path.write_text(
                                creds.to_json(),
                                encoding="utf-8",
                            )
                        except OSError:
                            logger.warning(
                                "Unable to update OAuth token file.",
                                exc_info=True,
                            )

                    if creds.valid:
                        self._drive = build(
                            "drive",
                            "v3",
                            credentials=creds,
                            cache_discovery=False,
                        )

                        logger.info(
                            "Google Drive authenticated using OAuth."
                        )

                        return self._drive

                except Exception:
                    logger.exception(
                        "Google Drive OAuth authentication failed."
                    )

        # --------------------------------------------------------------
        # Service-account JSON file fallback
        # --------------------------------------------------------------

        service_account_file = (
            os.getenv(
                "GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE",
                "",
            )
            .strip()
        )

        if service_account_file:

            path = Path(service_account_file)

            if not path.is_absolute():
                path = Path.cwd() / path

            if path.exists():

                try:
                    creds = (
                        service_account
                        .Credentials
                        .from_service_account_file(
                            str(path),
                            scopes=DRIVE_SCOPES,
                        )
                    )

                    self._drive = build(
                        "drive",
                        "v3",
                        credentials=creds,
                        cache_discovery=False,
                    )

                    logger.warning(
                        "Google Drive authenticated using "
                        "service account fallback."
                    )

                    return self._drive

                except Exception:
                    logger.exception(
                        "Service-account authentication failed."
                    )

        # --------------------------------------------------------------
        # Service-account JSON from environment
        # --------------------------------------------------------------

        service_account_json = (
            os.getenv(
                "GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON",
                "",
            )
            .strip()
        )

        if service_account_json:

            try:
                info = json.loads(service_account_json)

                creds = (
                    service_account
                    .Credentials
                    .from_service_account_info(
                        info,
                        scopes=DRIVE_SCOPES,
                    )
                )

                self._drive = build(
                    "drive",
                    "v3",
                    credentials=creds,
                    cache_discovery=False,
                )

                logger.warning(
                    "Google Drive authenticated using "
                    "service-account environment configuration."
                )

                return self._drive

            except Exception:
                logger.exception(
                    "Service-account JSON authentication failed."
                )

        raise RuntimeError(
            "Unable to authenticate with Google Drive. "
            "Configure GOOGLE_DRIVE_OAUTH_TOKEN_FILE."
        )

    # ==================================================================
    # BASIC DRIVE INFORMATION
    # ==================================================================

    def health_check(self) -> bool:
        """
        Check whether Google Drive is reachable and the configured
        root folder is accessible.
        """

        try:
            self.get_root_folder_metadata()
            return True

        except Exception:
            logger.exception(
                "Google Drive health check failed."
            )
            return False

    # ------------------------------------------------------------------

    def get_account_info(self) -> Dict[str, Any]:
        """Return information about the authenticated Google account."""

        drive = self._get_drive()

        result = (
            drive.about()
            .get(
                fields="user(displayName,permissionId,emailAddress)"
            )
            .execute()
        )

        return result.get("user", {})

    # ------------------------------------------------------------------

    def get_root_folder_metadata(self) -> Dict[str, Any]:
        """Return metadata for the configured root folder."""

        drive = self._get_drive()

        result = (
            drive.files()
            .get(
                fileId=self.root_folder_id,
                fields=(
                    "id,"
                    "name,"
                    "mimeType,"
                    "webViewLink,"
                    "createdTime,"
                    "modifiedTime"
                ),
            )
            .execute()
        )

        return result

    def list_files(
            self,
            parent_id: Optional[str] = None,
    ) -> list[Dict[str, Any]]:
        """List files and folders directly inside a Drive folder."""

        parent_id = parent_id or self.root_folder_id

        if not parent_id:
            raise ValueError("parent_id is required")

        drive = self._get_drive()

        query = (
            f"'{parent_id}' in parents "
            "and trashed = false"
        )

        result = (
            drive.files()
            .list(
                q=query,
                fields=(
                    "files("
                    "id,"
                    "name,"
                    "mimeType,"
                    "size,"
                    "parents,"
                    "webViewLink,"
                    "createdTime,"
                    "modifiedTime"
                    ")"
                ),
                orderBy="createdTime",
                pageSize=100,
            )
            .execute()
        )

        return result.get("files", [])

    # ==================================================================
    # FOLDER OPERATIONS
    # ==================================================================

    def create_folder(
        self,
        name: str,
        *,
        parent_id: Optional[str] = None,
    ) -> DriveAsset:
        """
        Create a Google Drive folder.

        If parent_id is omitted, the EventLah root folder is used.
        """

        name = (name or "").strip()

        if not name:
            raise ValueError(
                "Google Drive folder name cannot be empty."
            )

        parent_id = parent_id or self.root_folder_id

        drive = self._get_drive()

        body = {
            "name": name,
            "mimeType": FOLDER_MIME_TYPE,
            "parents": [parent_id],
        }

        result = (
            drive.files()
            .create(
                body=body,
                fields="id,name,mimeType",
            )
            .execute()
        )

        return DriveAsset(
            file_id=result["id"],
            filename=result.get("name", name),
            mime_type=result.get(
                "mimeType",
                FOLDER_MIME_TYPE,
            ),
            size=0,
        )

    # ------------------------------------------------------------------

    def find_folder(
        self,
        name: str,
        *,
        parent_id: Optional[str] = None,
    ) -> Optional[DriveAsset]:
        """
        Find an existing folder by name under a parent folder.

        Only non-trashed folders are considered.
        """

        name = (name or "").strip()

        if not name:
            return None

        parent_id = parent_id or self.root_folder_id

        drive = self._get_drive()

        escaped_name = name.replace("'", "\\'")

        query = (
            f"name = '{escaped_name}' "
            f"and mimeType = '{FOLDER_MIME_TYPE}' "
            f"and '{parent_id}' in parents "
            "and trashed = false"
        )

        result = (
            drive.files()
            .list(
                q=query,
                spaces="drive",
                fields=(
                    "files("
                    "id,"
                    "name,"
                    "mimeType"
                    ")"
                ),
                pageSize=10,
            )
            .execute()
        )

        files = result.get("files", [])

        if not files:
            return None

        item = files[0]

        return DriveAsset(
            file_id=item["id"],
            filename=item.get("name", name),
            mime_type=item.get(
                "mimeType",
                FOLDER_MIME_TYPE,
            ),
        )

    # ------------------------------------------------------------------

    def get_or_create_event_folder(
        self,
        event_name: str,
        *,
        event_id: Optional[int] = None,
        parent_id: Optional[str] = None,
    ) -> DriveAsset:
        """
        Find or create the Drive folder for an EventLah event.

        event_id is included in the folder name when available to avoid
        collisions between events with the same name.

        Example:

            Event #12 - Annual Dinner 2026
        """

        event_name = (event_name or "").strip()

        if not event_name:
            raise ValueError(
                "Event name is required to create an event folder."
            )

        if event_id is not None:
            folder_name = (
                f"Event #{event_id} - {event_name}"
            )
        else:
            folder_name = event_name

        parent_id = parent_id or self.root_folder_id

        existing = self.find_folder(
            folder_name,
            parent_id=parent_id,
        )

        if existing:
            return existing

        return self.create_folder(
            folder_name,
            parent_id=parent_id,
        )

    # ==================================================================
    # FILE OPERATIONS
    # ==================================================================

    def upload_bytes(
        self,
        data: bytes,
        filename: str,
        mime_type: str,
        *,
        parent_id: Optional[str] = None,
        overwrite: bool = False,
    ) -> DriveAsset:
        """
        Upload bytes to Google Drive.

        By default a new file is created.

        When overwrite=True, an existing file with the same name under
        the parent folder is updated.
        """

        if data is None:
            raise ValueError(
                "Upload data cannot be None."
            )

        if not isinstance(data, bytes):
            raise TypeError(
                "Upload data must be bytes."
            )

        filename = (filename or "").strip()

        if not filename:
            raise ValueError(
                "Filename cannot be empty."
            )

        mime_type = (
            mime_type
            or "application/octet-stream"
        ).strip()

        parent_id = parent_id or self.root_folder_id

        drive = self._get_drive()

        # --------------------------------------------------------------
        # Optional overwrite
        # --------------------------------------------------------------

        existing_file_id = None

        if overwrite:

            escaped_name = filename.replace("'", "\\'")

            query = (
                f"name = '{escaped_name}' "
                f"and '{parent_id}' in parents "
                "and trashed = false"
            )

            result = (
                drive.files()
                .list(
                    q=query,
                    spaces="drive",
                    fields="files(id,name,mimeType,size)",
                    pageSize=10,
                )
                .execute()
            )

            files = result.get("files", [])

            if files:
                existing_file_id = files[0]["id"]

        media = MediaIoBaseUpload(
            io.BytesIO(data),
            mimetype=mime_type,
            resumable=False,
        )

        # --------------------------------------------------------------
        # Update existing
        # --------------------------------------------------------------

        if existing_file_id:

            result = (
                drive.files()
                .update(
                    fileId=existing_file_id,
                    media_body=media,
                    fields="id,name,mimeType,size",
                )
                .execute()
            )

        # --------------------------------------------------------------
        # Create new
        # --------------------------------------------------------------

        else:

            body = {
                "name": filename,
                "parents": [parent_id],
            }

            result = (
                drive.files()
                .create(
                    body=body,
                    media_body=media,
                    fields="id,name,mimeType,size",
                )
                .execute()
            )

        return DriveAsset(
            file_id=result["id"],
            filename=result.get("name", filename),
            mime_type=result.get(
                "mimeType",
                mime_type,
            ),
            size=int(
                result.get("size", len(data))
                or len(data)
            ),
        )

    # ==================================================================
    # EVENT ASSETS
    # ==================================================================

    def upload_event_logo(
        self,
        data: bytes,
        filename: str,
        mime_type: str,
        *,
        event_folder_id: str,
    ) -> DriveAsset:
        """
        Upload an event logo into the event folder.
        """

        return self.upload_bytes(
            data=data,
            filename=filename,
            mime_type=mime_type,
            parent_id=event_folder_id,
            overwrite=True,
        )

    # ------------------------------------------------------------------

    def upload_event_invitation(
        self,
        data: bytes,
        filename: str,
        mime_type: str,
        *,
        event_folder_id: str,
    ) -> DriveAsset:
        """
        Upload an invitation card into the event folder.
        """

        return self.upload_bytes(
            data=data,
            filename=filename,
            mime_type=mime_type,
            parent_id=event_folder_id,
            overwrite=True,
        )

    # ==================================================================
    # GUEST LIST
    # ==================================================================
    def create_event_folder(
            self,
            folder_name: str,
    ) -> DriveAsset:
        """Create a dedicated folder inside the EventLah root folder."""

        if not folder_name or not folder_name.strip():
            raise ValueError("folder_name is required")

        if not self.root_folder_id:
            raise ValueError(
                "GOOGLE_DRIVE_ROOT_FOLDER_ID is not configured."
            )

        return self.create_folder(
            folder_name.strip(),
            parent_id=self.root_folder_id,
        )

    def upload_guest_list(
        self,
        data: bytes,
        filename: str,
        mime_type: str,
        *,
        event_folder_id: Optional[str] = None,
    ) -> DriveAsset:
        """
        Upload a guest-list file.

        If event_folder_id is provided, the file is stored inside the
        corresponding event folder.

        For backward compatibility, when event_folder_id is omitted,
        the file is uploaded to the EventLah root folder.
        """

        return self.upload_bytes(
            data=data,
            filename=filename,
            mime_type=mime_type,
            parent_id=(
                event_folder_id
                or self.root_folder_id
            ),
            overwrite=True,
        )

    # ==================================================================
    # DOWNLOAD
    # ==================================================================

    def download_bytes(
        self,
        file_id: str,
    ) -> bytes:
        """
        Download a Google Drive file as bytes.
        """

        file_id = (file_id or "").strip()

        if not file_id:
            raise ValueError(
                "Google Drive file ID is required."
            )

        drive = self._get_drive()

        request = drive.files().get(
            fileId=file_id,
            alt="media",
        )

        buffer = io.BytesIO()

        downloader = MediaIoBaseDownload(
            buffer,
            request,
        )

        done = False

        while not done:
            _, done = downloader.next_chunk()

        return buffer.getvalue()

    # ------------------------------------------------------------------

    def download_asset(
        self,
        file_id: str,
    ) -> bytes:
        """
        Compatibility alias for download_bytes().
        """

        return self.download_bytes(file_id)

    # ==================================================================
    # FILE METADATA
    # ==================================================================

    def get_file_metadata(
        self,
        file_id: str,
    ) -> Dict[str, Any]:
        """Return metadata for a Drive file."""

        file_id = (file_id or "").strip()

        if not file_id:
            raise ValueError(
                "Google Drive file ID is required."
            )

        drive = self._get_drive()

        return (
            drive.files()
            .get(
                fileId=file_id,
                fields=(
                    "id,"
                    "name,"
                    "mimeType,"
                    "size,"
                    "webViewLink,"
                    "parents,"
                    "createdTime,"
                    "modifiedTime,"
                    "trashed"
                ),
            )
            .execute()
        )

    # ==================================================================
    # DELETE
    # ==================================================================

    def delete_file(
            self,
            file_id: str,
    ) -> bool:
        """Move a Drive file or folder to trash."""

        if not file_id:
            raise ValueError("file_id is required")

        drive = self._get_drive()

        try:
            (
                drive.files()
                .update(
                    fileId=file_id,
                    body={"trashed": True},
                )
                .execute()
            )

            return True

        except HttpError:
            logger.exception(
                "Failed to delete Drive file %s",
                file_id,
            )
            return False

    # ==================================================================
    # MOVE
    # ==================================================================

    def move_file(
        self,
        file_id: str,
        *,
        new_parent_id: str,
    ) -> DriveAsset:
        """
        Move a Drive file into another folder.
        """

        if not file_id:
            raise ValueError(
                "file_id is required."
            )

        if not new_parent_id:
            raise ValueError(
                "new_parent_id is required."
            )

        drive = self._get_drive()

        metadata = (
            drive.files()
            .get(
                fileId=file_id,
                fields="id,name,mimeType,parents,size",
            )
            .execute()
        )

        old_parents = metadata.get(
            "parents",
            [],
        )

        result = (
            drive.files()
            .update(
                fileId=file_id,
                addParents=new_parent_id,
                removeParents=",".join(old_parents),
                fields="id,name,mimeType,size",
            )
            .execute()
        )

        return DriveAsset(
            file_id=result["id"],
            filename=result.get(
                "name",
                metadata.get("name", ""),
            ),
            mime_type=result.get(
                "mimeType",
                metadata.get("mimeType", ""),
            ),
            size=int(
                result.get(
                    "size",
                    metadata.get("size", 0),
                )
                or 0
            ),
        )